### ISSUE TITLE
GitHub Action testing multiple versions of Docker

### ISSUE THREAD

**Issue by MickMake** [gearboxworks/launch#24]
https://stackoverflow.com/questions/59363727/using-a-specific-docker-version-in-github-actions

```
name: Check Docker Version

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Docker Version
      run: docker --version
    - name: Install Latest Docker
      run: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
        sudo apt-get update
        sudo apt-get install docker-ce
    - name: Check Docker Version
      run: docker --version
```
